// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function make(declaration) {
  var match = declaration.VAL;
  return [
          match[0],
          match[1]
        ];
}

function map(declaration, callback) {
  return Curry._1(callback, declaration);
}

function declarationFn(property, value) {
  return {
          NAME: "DeclarationFn",
          VAL: [
            property,
            value
          ]
        };
}

var Helper = {
  declarationFn: declarationFn
};

exports.make = make;
exports.map = map;
exports.Helper = Helper;
/* No side effect */
